export const GAME_CONSTANTS = {
  ORDER: 7,
  MAX_PLAYERS: 8,
  MIN_PLAYERS: 2,
  STARTING_COUNTDOWN_SECONDS: 5,
  TOTAL_CARDS: 57,
  SYMBOLS_PER_CARD: 8,
  AVALANCHE_STARTING_HAND: 1,
  EVENTS: {
    MATCH_ATTEMPT: "MATCH_ATTEMPT",
    MATCH_SUCCESS: "MATCH_SUCCESS",
    MATCH_FAIL: "MATCH_FAIL",
    GAME_START: "GAME_START",
    GAME_OVER: "GAME_OVER"
  }
};
